### ISSUE TITLE
[Release vx.xx]: 1 Day Prior to Release Checklist

### ISSUE THREAD

**Issue by carlisia** [carlisia/carlisia#2]
### Which tasks have been fully completed?

- [ ] All items on the "7 Days Prior to Release Checklist" have been checked off
- [ ] Readiness has been confirmed for each repo
- [ ] Nighly builds have been checked for each repo
- [ ] A new GitHub issue for the "Day of Release - First Batch of Repos Checklist" has been created
