### ISSUE TITLE
[Release vx.xx]: 14 Days Prior to Release Checklist

### ISSUE THREAD

**Issue by carlisia** [carlisia/carlisia#3]
### Which tasks have been fully completed?

- [ ] All items on the "First Week of Rotation Checklist" have been checked off
- [ ] The Knative releasability defaults have been updated
- [ ] A new GitHub issue for the "7 Days Prior to Release Checklist" has been created
