### ISSUE TITLE
[Release vx.xx]: Second Batch of Repos Checklist

### ISSUE THREAD

**Issue by carlisia** [carlisia/carlisia#5]
### Please only check each repo as done after it has been successfully released and published. The repos in this checklist can only be cut after the `eventing` repo has been released and published https://github.com/knative/eventing/releases, testing link ->  [eventing releases](https://github.com/knative/eventing/releases). \n Please also ensure that there are no outstanding PRs for each repo before cutting its release branch. Please see the full release instructions for details (https://github.com/knative/release/blob/0f481ee5e96a9bb9b515c4bc151e541d93bc05c7/INSTRUCTIONS.md. Or, Please see the full [release instructions for details](https://github.com/knative/release/blob/0f481ee5e96a9bb9b515c4bc151e541d93bc05c7/INSTRUCTIONS.md).

- [ ] All items on the "Release - First Batch of Repos Checklist" have been checked off
- [ ] knative.dev/eventing-ceph
- [ ] knative.dev/eventing-kogito
- [ ] knative.dev/eventing-nats
- [ ] knative.dev/eventing-rabbitmq
- [ ] knative.dev/sample-source
- [ ] A new GitHub issue for the "Release - Third Batch of Repos Checklist" has been created
