### ISSUE TITLE
[Release vx.xx]: Second Batch of Repos Checklist

### ISSUE THREAD

**Issue by carlisia** [carlisia/carlisia#7]
### Please only mark each repo as done after it has been verified as released and published.

- [X] All items on the "Release - First Batch of Repos Checklist" have been checked off
- [ ] knative.dev/eventing-ceph
- [ ] knative.dev/eventing-kogito
- [ ] knative.dev/eventing-nats
- [ ] knative.dev/eventing-rabbitmq
- [ ] knative.dev/sample-source
- [ ] A new GitHub issue for the "Release - Third Batch of Repos Checklist" has been created
